/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "server-rpc-builder.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
print_datetime_1(entry *argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, print_datetime,
		(xdrproc_t) xdr_entry, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
