/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "server-rpc-builder.h"

bool_t
xdr_entry (XDR *xdrs, entry *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->username, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operation, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->filename, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->datetime, 256))
		 return FALSE;
	return TRUE;
}
