/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVER-RPC-BUILDER_H_RPCGEN
#define _SERVER-RPC-BUILDER_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct entry {
	char *username;
	char *operation;
	char *filename;
	char *datetime;
};
typedef struct entry entry;

#define RPC_SERVICE_DATETIME 100495794
#define RPC_SERVICE 1

#if defined(__STDC__) || defined(__cplusplus)
#define print_datetime 1
extern  enum clnt_stat print_datetime_1(entry *, int *, CLIENT *);
extern  bool_t print_datetime_1_svc(entry *, int *, struct svc_req *);
extern int rpc_service_datetime_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define print_datetime 1
extern  enum clnt_stat print_datetime_1();
extern  bool_t print_datetime_1_svc();
extern int rpc_service_datetime_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_entry (XDR *, entry*);

#else /* K&R C */
extern bool_t xdr_entry ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVER-RPC-BUILDER_H_RPCGEN */
